class CreateProvinces < ActiveRecord::Migration
  def change
    create_table :provinces do |t|
      t.string :province

      t.timestamps
    end

    Province.create!(:province => 'Unidentify')
    Province.create!(:province => 'Bangkok Metropolis')
    #North
    Province.create!(:province => 'North')
    Province.create!(:province => 'Kamphaeng Phet')
    Province.create!(:province => 'Chiang Rai')
    Province.create!(:province => 'Chiang Mai')
    Province.create!(:province => 'Tak')
    Province.create!(:province => 'Nakhon Sawan')
    Province.create!(:province => 'Nan')
    Province.create!(:province => 'Phichit')
    Province.create!(:province => 'Phitsanulok')
    Province.create!(:province => 'Phetchabun')
    Province.create!(:province => 'Phrae')
    Province.create!(:province => 'Mae Hong Son')
    Province.create!(:province => 'Lampang')
    Province.create!(:province => 'Lamphun')
    Province.create!(:province => 'Sukhothai')
    Province.create!(:province => 'Uttaradit')
    Province.create!(:province => 'Uthai Thani')
    Province.create!(:province => 'Phayao')
    #Central Region
    Province.create!(:province => 'Central Region')
    Province.create!(:province => 'Kanchanaburi')
    Province.create!(:province => 'Chanthaburi')
    Province.create!(:province => 'Chachoengsao')
    Province.create!(:province => 'Chon Buri')
    Province.create!(:province => 'Chai Nat')
    Province.create!(:province => 'Trat')
    Province.create!(:province => 'Nakhon Nayok')
    Province.create!(:province => 'Nakhon Pathom')
    Province.create!(:province => 'Nonthaburi')
    Province.create!(:province => 'Pathum Thani')
    Province.create!(:province => 'Prachuap Khiri Khan')
    Province.create!(:province => 'Prachin Buri')
    Province.create!(:province => 'Phra Nakhon Si Ayutthaya')
    Province.create!(:province => 'Phetchaburi')
    Province.create!(:province => 'Rayong')
    Province.create!(:province => 'Ratchaburi')
    Province.create!(:province => 'Lop Buri')
    Province.create!(:province => 'Samut Prakan')
    Province.create!(:province => 'Samut Songkhram')
    Province.create!(:province => 'Samut Sakhon')
    Province.create!(:province => 'Saraburi')
    Province.create!(:province => 'Sing Buri')
    Province.create!(:province => 'Suphan Buri')
    Province.create!(:province => 'Ang Thong')
    Province.create!(:province => 'Sa Kaeo')
    #Northeast
    Province.create!(:province => 'Northeast')
    Province.create!(:province => 'Kalasin')
    Province.create!(:province => 'Khon Kaen')
    Province.create!(:province => 'Chaiyaphum')
    Province.create!(:province => 'Yasothon')
    Province.create!(:province => 'Nakhon Phanom')
    Province.create!(:province => 'Nakhon Ratchasima')
    Province.create!(:province => 'Buri Ram')
    Province.create!(:province => 'Maha Sarakham')
    Province.create!(:province => 'Roi Et')
    Province.create!(:province => 'Loei')
    Province.create!(:province => 'Si Sa Ket')
    Province.create!(:province => 'Sakon Nakhon')
    Province.create!(:province => 'Surin')
    Province.create!(:province => 'Nong Khai')
    Province.create!(:province => 'Udon Thani')
    Province.create!(:province => 'Ubon Ratchathani')
    Province.create!(:province => 'Mukdahan')
    Province.create!(:province => 'Amnat Charoen')
    Province.create!(:province => 'Nong Bua Lam Phu')
    #South
    Province.create!(:province => 'South')
    Province.create!(:province => 'Krabi')
    Province.create!(:province => 'Chumphon')
    Province.create!(:province => 'Trang')
    Province.create!(:province => 'Nakhon Si Thammarat')
    Province.create!(:province => 'Narathiwat')
    Province.create!(:province => 'Pattani')
    Province.create!(:province => 'Phangnga')
    Province.create!(:province => 'Phatthalung')
    Province.create!(:province => 'Phuket')
    Province.create!(:province => 'Yala')
    Province.create!(:province => 'Ranong')
    Province.create!(:province => 'Songkhla')
    Province.create!(:province => 'Satun')
    Province.create!(:province => 'Surat Thani')
    
  end
end
